### ISSUE TITLE
[T017] Navegando como subscriptor en un despliegue en linea, el comportamiento es erratico y mucho links aun apuntan a localhost

### ISSUE THREAD

**Issue by juanmanuelgg** [aanieves/Ghost#13]
### COMPORTAMIENTO ESPERADO:
Se debería ver una navegación natural como si se puede ver en un despliegue local.

### COMPORTAMIENTO ACTUAL:
Los links no funcionan y es errático que algunos apunten a localhost y otros conserven el dominio asignado en el archivo de configuración.

### PASOS PARA REPRODUCIR DEFECTO:

```nginx
server {

  server_name ghost.appbajopruebas.com, www.ghost.appbajopruebas.com;

  location / {
    # auth_basic "Restricted Content";
    # auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass http://localhost:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  listen [::]:443 ssl; # managed by Certbot
  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/ghost.appbajopruebas.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/ghost.appbajopruebas.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
  if ($host = www.ghost.appbajopruebas.com) {
     return 301 https://$host$request_uri;
  } # managed by Certbot

  if ($host = ghost.appbajopruebas.com) {
    return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80 default_server;
  listen [::]:80 default_server;
  server_name ghost.appbajopruebas.com, www.ghost.appbajopruebas.com;
  return 404; # managed by Certbot
}
```

```yaml
# Construido sobre: https://hub.docker.com/_/ghost/
# Sección: Production mode ... via docker stack deploy or docker-compose
version: "3.1"

name: pruebas-ghost

services:
  ghost:
    container_name: ghost
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: X02kt6Nr014E74I24Sx8
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      # - ./volumes/ghost:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json
      - ghost:/var/lib/ghost/content

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
     - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: X02kt6Nr014E74I24Sx8
    volumes:
      # - ./volumes/db:/var/lib/mysql
      - db:/var/lib/mysql

volumes:
  ghost:
  db:

```

```json
{
  "url": "http://localhost:2368",
  "server": {
    "port": 2368,
    "host": "::"
  },
  "mail": {
    "transport": "SMTP",
    "options": {
      "host": "smtpout.secureserver.net",
      "port": 465,
      "secure": true,
      "from": "'Robot Automatizacion' <automatizacion@appbajopruebas.com>",
      "auth": {
        "user": "automatizacion@appbajopruebas.com",
        "pass": "XXXX_ESTE_SECRETO_DEBE_SER_REEMPLAZADO_XXXX"
      }
    }
  },
  "logging": {
    "transports": ["file", "stdout"]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}
```

### CONTEXTO:

Versión de la App: Ghost Versión [5.82.0](https://github.com/TryGhost/Ghost/releases/tag/v5.82.0) ([b6195d](https://github.com/TryGhost/Ghost/tree/b6195d204cf395b7216a63c4dde2cd1775f52948))
Sistema Operativo: Linux 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Navegador: Google Chrome Versión 123.0.6312.106 (Build oficial) (64 bits).

### INFORMACIÓN ADICIONAL:

Observar esquina inferior izquierda
![Screenshot from 2024-04-07 22-13-16](https://github.com/aanieves/Ghost/assets/3623420/a74ba4b4-1a78-43e7-9711-95e0c8d1a728)
